// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"context"
	"github.com/crazyfrankie/cronjob/master/conf"
	"github.com/crazyfrankie/cronjob/master/handler"
	"github.com/crazyfrankie/cronjob/master/service"
	"github.com/gin-gonic/gin"
	"go.etcd.io/etcd/client/v3"
	"go.mongodb.org/mongo-driver/v2/event"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"time"
)

// Injectors from wire.go:

func InitServer() *gin.Engine {
	client := InitETCD()
	jobService := service.NewJobService(client)
	database := InitMongo()
	logService := service.NewLogService(database)
	workerService := service.NewWorkerService(client)
	jobHandler := handler.NewJobHandler(jobService, logService, workerService)
	engine := InitGin(jobHandler)
	return engine
}

// wire.go:

func InitETCD() *clientv3.Client {
	client, err := clientv3.New(clientv3.Config{
		Endpoints:   conf.GetConf().ETCD.Endpoint,
		DialTimeout: time.Duration(conf.GetConf().ETCD.ConnectTimeOut),
	})
	if err != nil {
		panic(err)
	}

	return client
}

func InitMongo() *mongo.Database {
	monitor := &event.CommandMonitor{}

	opt := options.Client().ApplyURI(conf.GetConf().Mongo.URI).
		SetMonitor(monitor).SetConnectTimeout(time.Duration(conf.GetConf().ETCD.ConnectTimeOut))
	client, err := mongo.Connect(opt)
	if err != nil {
		panic(err)
	}

	db := client.Database("cronjob")
	err = InitMongoCollections(db)
	if err != nil {
		panic(err)
	}

	return db
}

func InitMongoCollections(db *mongo.Database) error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
	defer cancel()

	if err := db.CreateCollection(ctx, "cron_job_logs"); err != nil {
		return err
	}

	return nil
}

func InitGin(job *handler.JobHandler) *gin.Engine {
	srv := gin.Default()

	job.RegisterRoute(srv)

	return srv
}
